[package]
name = "vk-ext-mesh-shader-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
ash = { git = "https://github.com/projectkml/ash", branch = "ext-mesh-shader" }
ash-window = { git = "https://github.com/projectkml/ash", branch = "ext-mesh-shader" }
dolly = "0.3.1"
glam = "0.21.3"
vk-mem-alloc = { git = "https://github.com/projectkml/vk-mem-alloc-rs" }
winit = "0.27.2"