edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 187
reorder_imports = true
trailing_comma = "Never"
trailing_semicolon = false
unstable_features = true